import os

os.system('pip install pyautogui')
os.system('pip install shutil')
os.system('pip install pyTelegramBotAPI')
os.system('pip install keyboard')
os.system('pip install ctypes') 
os.system('pip install winreg')
os.system('pip install subprocess')
os.system('pip install win32api')
os.system('pip install pyinstaller')
os.system('pip install configparser')
os.system('pip install pillow')
os.system('pip install screen_brightness_control')
os.system('pip install psutil')